// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig } from '@hey-api/client-fetch';
import { getApiBaseUrl } from '@/lib/api-base';

export const client = createClient(
  createConfig({
    baseUrl: getApiBaseUrl(),
  })
);
