// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig } from '@hey-api/client-fetch';

export const client = createClient(
  createConfig({
    baseUrl: import.meta.env.VITE_API_BASE_URL || '', // Falls back to relative paths for dev proxy
  })
);
