[project]
name = "logging-server"
version = "0.1.0"
description = "Solar logging server template"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "python-dotenv>=1.1.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.1",
    "websockets>=15.0.1",
]
