name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        working-directory: services
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Static import checks
        run: |
          python -m compileall -q services
          python -c "import api.bootstrap, core.render_queue, core.ffmpeg_service; print('Imports OK')"

      - name: Lint with ruff
        working-directory: services
        run: |
          pip install ruff
          ruff check .
          ruff format --check .

      - name: Run tests with pytest
        working-directory: services
        run: |
          pip install pytest pytest-asyncio pytest-mock
          pytest tests/ -v --tb=short

  frontend-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        working-directory: app
        run: pnpm install --frozen-lockfile

      - name: Type check
        working-directory: app
        run: pnpm exec tsc --noEmit

      - name: Build
        working-directory: app
        run: pnpm build

  container-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services image
        uses: docker/build-push-action@v6
        with:
          context: ./services
          file: ./services/Dockerfile
          push: false
          tags: local/magiclens-services:ci